export interface Country {
  code: string;
  name: string;
  flag: string;
  phoneCode: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", flag: "\u{1F1E6}\u{1F1EB}", phoneCode: "+93" },
  { code: "AL", name: "Albania", flag: "\u{1F1E6}\u{1F1F1}", phoneCode: "+355" },
  { code: "DZ", name: "Algeria", flag: "\u{1F1E9}\u{1F1FF}", phoneCode: "+213" },
  { code: "AR", name: "Argentina", flag: "\u{1F1E6}\u{1F1F7}", phoneCode: "+54" },
  { code: "AU", name: "Australia", flag: "\u{1F1E6}\u{1F1FA}", phoneCode: "+61" },
  { code: "AT", name: "Austria", flag: "\u{1F1E6}\u{1F1F9}", phoneCode: "+43" },
  { code: "AZ", name: "Azerbaijan", flag: "\u{1F1E6}\u{1F1FF}", phoneCode: "+994" },
  { code: "BD", name: "Bangladesh", flag: "\u{1F1E7}\u{1F1E9}", phoneCode: "+880" },
  { code: "BE", name: "Belgium", flag: "\u{1F1E7}\u{1F1EA}", phoneCode: "+32" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "\u{1F1E7}\u{1F1E6}", phoneCode: "+387" },
  { code: "BR", name: "Brazil", flag: "\u{1F1E7}\u{1F1F7}", phoneCode: "+55" },
  { code: "BG", name: "Bulgaria", flag: "\u{1F1E7}\u{1F1EC}", phoneCode: "+359" },
  { code: "CA", name: "Canada", flag: "\u{1F1E8}\u{1F1E6}", phoneCode: "+1" },
  { code: "CL", name: "Chile", flag: "\u{1F1E8}\u{1F1F1}", phoneCode: "+56" },
  { code: "CN", name: "China", flag: "\u{1F1E8}\u{1F1F3}", phoneCode: "+86" },
  { code: "CO", name: "Colombia", flag: "\u{1F1E8}\u{1F1F4}", phoneCode: "+57" },
  { code: "HR", name: "Croatia", flag: "\u{1F1ED}\u{1F1F7}", phoneCode: "+385" },
  { code: "CZ", name: "Czech Republic", flag: "\u{1F1E8}\u{1F1FF}", phoneCode: "+420" },
  { code: "DK", name: "Denmark", flag: "\u{1F1E9}\u{1F1F0}", phoneCode: "+45" },
  { code: "EG", name: "Egypt", flag: "\u{1F1EA}\u{1F1EC}", phoneCode: "+20" },
  { code: "EE", name: "Estonia", flag: "\u{1F1EA}\u{1F1EA}", phoneCode: "+372" },
  { code: "FI", name: "Finland", flag: "\u{1F1EB}\u{1F1EE}", phoneCode: "+358" },
  { code: "FR", name: "France", flag: "\u{1F1EB}\u{1F1F7}", phoneCode: "+33" },
  { code: "GE", name: "Georgia", flag: "\u{1F1EC}\u{1F1EA}", phoneCode: "+995" },
  { code: "DE", name: "Germany", flag: "\u{1F1E9}\u{1F1EA}", phoneCode: "+49" },
  { code: "GR", name: "Greece", flag: "\u{1F1EC}\u{1F1F7}", phoneCode: "+30" },
  { code: "HU", name: "Hungary", flag: "\u{1F1ED}\u{1F1FA}", phoneCode: "+36" },
  { code: "IN", name: "India", flag: "\u{1F1EE}\u{1F1F3}", phoneCode: "+91" },
  { code: "ID", name: "Indonesia", flag: "\u{1F1EE}\u{1F1E9}", phoneCode: "+62" },
  { code: "IR", name: "Iran", flag: "\u{1F1EE}\u{1F1F7}", phoneCode: "+98" },
  { code: "IQ", name: "Iraq", flag: "\u{1F1EE}\u{1F1F6}", phoneCode: "+964" },
  { code: "IE", name: "Ireland", flag: "\u{1F1EE}\u{1F1EA}", phoneCode: "+353" },
  { code: "IL", name: "Israel", flag: "\u{1F1EE}\u{1F1F1}", phoneCode: "+972" },
  { code: "IT", name: "Italy", flag: "\u{1F1EE}\u{1F1F9}", phoneCode: "+39" },
  { code: "JP", name: "Japan", flag: "\u{1F1EF}\u{1F1F5}", phoneCode: "+81" },
  { code: "JO", name: "Jordan", flag: "\u{1F1EF}\u{1F1F4}", phoneCode: "+962" },
  { code: "KZ", name: "Kazakhstan", flag: "\u{1F1F0}\u{1F1FF}", phoneCode: "+7" },
  { code: "KE", name: "Kenya", flag: "\u{1F1F0}\u{1F1EA}", phoneCode: "+254" },
  { code: "KR", name: "South Korea", flag: "\u{1F1F0}\u{1F1F7}", phoneCode: "+82" },
  { code: "KW", name: "Kuwait", flag: "\u{1F1F0}\u{1F1FC}", phoneCode: "+965" },
  { code: "LV", name: "Latvia", flag: "\u{1F1F1}\u{1F1FB}", phoneCode: "+371" },
  { code: "LB", name: "Lebanon", flag: "\u{1F1F1}\u{1F1E7}", phoneCode: "+961" },
  { code: "LT", name: "Lithuania", flag: "\u{1F1F1}\u{1F1F9}", phoneCode: "+370" },
  { code: "MY", name: "Malaysia", flag: "\u{1F1F2}\u{1F1FE}", phoneCode: "+60" },
  { code: "MX", name: "Mexico", flag: "\u{1F1F2}\u{1F1FD}", phoneCode: "+52" },
  { code: "MA", name: "Morocco", flag: "\u{1F1F2}\u{1F1E6}", phoneCode: "+212" },
  { code: "NL", name: "Netherlands", flag: "\u{1F1F3}\u{1F1F1}", phoneCode: "+31" },
  { code: "NZ", name: "New Zealand", flag: "\u{1F1F3}\u{1F1FF}", phoneCode: "+64" },
  { code: "NG", name: "Nigeria", flag: "\u{1F1F3}\u{1F1EC}", phoneCode: "+234" },
  { code: "NO", name: "Norway", flag: "\u{1F1F3}\u{1F1F4}", phoneCode: "+47" },
  { code: "PK", name: "Pakistan", flag: "\u{1F1F5}\u{1F1F0}", phoneCode: "+92" },
  { code: "PE", name: "Peru", flag: "\u{1F1F5}\u{1F1EA}", phoneCode: "+51" },
  { code: "PH", name: "Philippines", flag: "\u{1F1F5}\u{1F1ED}", phoneCode: "+63" },
  { code: "PL", name: "Poland", flag: "\u{1F1F5}\u{1F1F1}", phoneCode: "+48" },
  { code: "PT", name: "Portugal", flag: "\u{1F1F5}\u{1F1F9}", phoneCode: "+351" },
  { code: "QA", name: "Qatar", flag: "\u{1F1F6}\u{1F1E6}", phoneCode: "+974" },
  { code: "RO", name: "Romania", flag: "\u{1F1F7}\u{1F1F4}", phoneCode: "+40" },
  { code: "RU", name: "Russia", flag: "\u{1F1F7}\u{1F1FA}", phoneCode: "+7" },
  { code: "SA", name: "Saudi Arabia", flag: "\u{1F1F8}\u{1F1E6}", phoneCode: "+966" },
  { code: "RS", name: "Serbia", flag: "\u{1F1F7}\u{1F1F8}", phoneCode: "+381" },
  { code: "SG", name: "Singapore", flag: "\u{1F1F8}\u{1F1EC}", phoneCode: "+65" },
  { code: "SK", name: "Slovakia", flag: "\u{1F1F8}\u{1F1F0}", phoneCode: "+421" },
  { code: "SI", name: "Slovenia", flag: "\u{1F1F8}\u{1F1EE}", phoneCode: "+386" },
  { code: "ZA", name: "South Africa", flag: "\u{1F1FF}\u{1F1E6}", phoneCode: "+27" },
  { code: "ES", name: "Spain", flag: "\u{1F1EA}\u{1F1F8}", phoneCode: "+34" },
  { code: "SE", name: "Sweden", flag: "\u{1F1F8}\u{1F1EA}", phoneCode: "+46" },
  { code: "CH", name: "Switzerland", flag: "\u{1F1E8}\u{1F1ED}", phoneCode: "+41" },
  { code: "TH", name: "Thailand", flag: "\u{1F1F9}\u{1F1ED}", phoneCode: "+66" },
  { code: "TR", name: "Turkey", flag: "\u{1F1F9}\u{1F1F7}", phoneCode: "+90" },
  { code: "UA", name: "Ukraine", flag: "\u{1F1FA}\u{1F1E6}", phoneCode: "+380" },
  { code: "AE", name: "United Arab Emirates", flag: "\u{1F1E6}\u{1F1EA}", phoneCode: "+971" },
  { code: "GB", name: "United Kingdom", flag: "\u{1F1EC}\u{1F1E7}", phoneCode: "+44" },
  { code: "US", name: "United States", flag: "\u{1F1FA}\u{1F1F8}", phoneCode: "+1" },
  { code: "UZ", name: "Uzbekistan", flag: "\u{1F1FA}\u{1F1FF}", phoneCode: "+998" },
  { code: "VN", name: "Vietnam", flag: "\u{1F1FB}\u{1F1F3}", phoneCode: "+84" },
].sort((a, b) => a.name.localeCompare(b.name));
